version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - RAILS_ENV=${RAILS_ENV:-development}
    ports:
      - "3000:3000"
    volumes:
      - ${RAILS_ENV:-development} == development ? .:/app : /app/public
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_URL: postgres://postgres:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-myapp_development}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-myapp_development}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    profiles:
      - production

volumes:
  postgres_data: 